/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'typingTimestamp' : IDL.Int,
  'profileImageId' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'partnerEmail' : IDL.Text,
  'email' : IDL.Text,
  'partnerId' : IDL.Opt(IDL.Principal),
  'isTyping' : IDL.Bool,
  'passwordHash' : IDL.Text,
  'lastSeen' : IDL.Int,
  'online' : IDL.Bool,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Nat,
  'content' : IDL.Text,
  'receiverId' : IDL.Principal,
  'timestamp' : IDL.Int,
  'senderId' : IDL.Principal,
});
export const LoginInput = IDL.Record({
  'email' : IDL.Text,
  'passwordHash' : IDL.Text,
});
export const RegistrationInput = IDL.Record({
  'name' : IDL.Text,
  'partnerEmail' : IDL.Text,
  'email' : IDL.Text,
  'passwordHash' : IDL.Text,
});
export const MessageInput = IDL.Record({
  'content' : IDL.Text,
  'receiverId' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMessages' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Nat],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getOwnProfile' : IDL.Func([], [UserProfile], ['query']),
  'getOwnProfileImageId' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getPartnerTyping' : IDL.Func([], [IDL.Bool], ['query']),
  'getProfilePictureId' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getUnreadMessageCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasImageId' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func([LoginInput], [IDL.Bool], ['query']),
  'markAsRead' : IDL.Func([IDL.Principal], [], []),
  'register' : IDL.Func([RegistrationInput], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([MessageInput], [], []),
  'setProfilePicture' : IDL.Func([IDL.Text], [], []),
  'setTyping' : IDL.Func([IDL.Bool], [], []),
  'updateOnlineStatus' : IDL.Func([IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'typingTimestamp' : IDL.Int,
    'profileImageId' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'partnerEmail' : IDL.Text,
    'email' : IDL.Text,
    'partnerId' : IDL.Opt(IDL.Principal),
    'isTyping' : IDL.Bool,
    'passwordHash' : IDL.Text,
    'lastSeen' : IDL.Int,
    'online' : IDL.Bool,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Nat,
    'content' : IDL.Text,
    'receiverId' : IDL.Principal,
    'timestamp' : IDL.Int,
    'senderId' : IDL.Principal,
  });
  const LoginInput = IDL.Record({
    'email' : IDL.Text,
    'passwordHash' : IDL.Text,
  });
  const RegistrationInput = IDL.Record({
    'name' : IDL.Text,
    'partnerEmail' : IDL.Text,
    'email' : IDL.Text,
    'passwordHash' : IDL.Text,
  });
  const MessageInput = IDL.Record({
    'content' : IDL.Text,
    'receiverId' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMessages' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Nat],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getOwnProfile' : IDL.Func([], [UserProfile], ['query']),
    'getOwnProfileImageId' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getPartnerTyping' : IDL.Func([], [IDL.Bool], ['query']),
    'getProfilePictureId' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getUnreadMessageCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasImageId' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func([LoginInput], [IDL.Bool], ['query']),
    'markAsRead' : IDL.Func([IDL.Principal], [], []),
    'register' : IDL.Func([RegistrationInput], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([MessageInput], [], []),
    'setProfilePicture' : IDL.Func([IDL.Text], [], []),
    'setTyping' : IDL.Func([IDL.Bool], [], []),
    'updateOnlineStatus' : IDL.Func([IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };