/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface LoginInput { 'email' : string, 'passwordHash' : string }
export interface Message {
  'id' : bigint,
  'status' : bigint,
  'content' : string,
  'receiverId' : Principal,
  'timestamp' : bigint,
  'senderId' : Principal,
}
export interface MessageInput { 'content' : string, 'receiverId' : Principal }
export interface RegistrationInput {
  'name' : string,
  'partnerEmail' : string,
  'email' : string,
  'passwordHash' : string,
}
export interface SafeUserProfile {
  'typingTimestamp' : bigint,
  'profileImageId' : [] | [string],
  'name' : string,
  'partnerEmail' : string,
  'email' : string,
  'partnerId' : [] | [Principal],
  'isTyping' : boolean,
  'lastSeen' : bigint,
  'online' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'generateTOTPSecret' : ActorMethod<[string], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [SafeUserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMessages' : ActorMethod<[Principal, bigint, bigint], Array<Message>>,
  'getOrCreateProfile' : ActorMethod<[string], { 'isNew' : boolean }>,
  'getOwnProfile' : ActorMethod<[], SafeUserProfile>,
  'getOwnProfileImageId' : ActorMethod<[], [] | [string]>,
  'getPartnerTyping' : ActorMethod<[], boolean>,
  'getProfilePictureId' : ActorMethod<[Principal], [] | [string]>,
  'getUnreadMessageCount' : ActorMethod<[Principal], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [SafeUserProfile]>,
  'hasImageId' : ActorMethod<[string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'login' : ActorMethod<[LoginInput], boolean>,
  'markAsRead' : ActorMethod<[Principal], undefined>,
  'register' : ActorMethod<[RegistrationInput], undefined>,
  'saveCallerUserProfile' : ActorMethod<[SafeUserProfile], undefined>,
  'sendMessage' : ActorMethod<[MessageInput], undefined>,
  'setProfilePicture' : ActorMethod<[string], undefined>,
  'setTyping' : ActorMethod<[boolean], undefined>,
  'updateOnlineStatus' : ActorMethod<[boolean], undefined>,
  'verifyTOTP' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];